"""
Prompts package for Cold Outreach Agent.
"""

from prompts.candidate import CANDIDATE_PROFILE, CANDIDATE_CV, EXAMPLE_COVER_LETTER
from prompts.researcher import (
    RESEARCHER_QUERY_SYSTEM_PROMPT,
    RESEARCHER_QUERY_HUMAN_PROMPT,
    EXTRACTION_SYSTEM_PROMPT,
    COMPANY_NAME_FALLBACK_PROMPT,
    RESEARCH_EVALUATION_SYSTEM_PROMPT,
)
from prompts.cover_writer import (
    COVER_LETTER_SYSTEM_TEMPLATE,
    COVER_LETTER_HUMAN_PROMPT,
    COVER_LETTER_EVALUATION_TEMPLATE,
)
from prompts.email_writer import (
    EMAIL_WRITER_SYSTEM_TEMPLATE,
    EMAIL_WRITER_HUMAN_PROMPT,
    EMAIL_EVALUATION_TEMPLATE,
    EMAIL_SUBJECT_SYSTEM_TEMPLATE,
)

__all__ = [
    "CANDIDATE_PROFILE",
    "CANDIDATE_CV",
    "EXAMPLE_COVER_LETTER",
    "RESEARCHER_QUERY_SYSTEM_PROMPT",
    "RESEARCHER_QUERY_HUMAN_PROMPT",
    "EXTRACTION_SYSTEM_PROMPT",
    "COMPANY_NAME_FALLBACK_PROMPT",
    "RESEARCH_EVALUATION_SYSTEM_PROMPT",
    "COVER_LETTER_SYSTEM_TEMPLATE",
    "COVER_LETTER_HUMAN_PROMPT",
    "COVER_LETTER_EVALUATION_TEMPLATE",
    "EMAIL_WRITER_SYSTEM_TEMPLATE",
    "EMAIL_WRITER_HUMAN_PROMPT",
    "EMAIL_EVALUATION_TEMPLATE",
    "EMAIL_SUBJECT_SYSTEM_TEMPLATE",
]

